# Generated by Django 3.2.4 on 2022-03-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_flan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
