# Generated by Django 3.2.4 on 2022-03-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_locales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locales',
            new_name='Local',
        ),
    ]
